name: Flux Automatic Pull Request
on:
  push:
    branches: ['flux-production-image-updates']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "This PR was created due to Flux ImageUpdateAutomation configuration"
        pr_reviewer: "jaimeniswonger"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}